### ISSUE TITLE
[Model] VOD, Content 추천 결과 결합 및 신규 유저 처리

### ISSUE THREAD

**Issue by Junoflows** [LGHV-team1/final-project#263]
## 💡 목적
VOD, Content 추천 결과 결합 및 신규 유저 처리

## 💻 작업 상세 내용

- [x] VOD 추천 결과와 VOD 데이터에 없는 유저의 추천 결과는 content 추천 결과에서 가져옴
- [x] 신규 유저에게  VOD 5개를 입력받으면 이 VOD로 실시간으로 모델을 돌려 추천 결과를 도출하도록

## ❗️ 참고 사항
- [x] 위 과정을 함수로 표현할 것

**Comment by dhyeon1320** [comment]
장르 기반 함수 완료했습니다! 두 분 하시면 체크하시면 돼요
