### ISSUE TITLE
[Model] Content 데이터 처리

### ISSUE THREAD

**Issue by sugenre** [LGHV-team1/final-project#30]
## 💡 목적
> Content 8, 9월 데이터 병합 & 전처리

## 💻 작업 상세 내용

- [x] con89, vod89 생성
- [x] 모든 기호, 괄호 안의 내용 제거
- [x] 회차 제거
- [x] series null값 채우기
- [x] score 변수 생성
- [x] 변수 생성하고 순서 바꾸기
- [x] id, 프로그램명을 기준으로 중복 값 삭제
- [x] 전처리 내용 재확인

## ❗️ 참고 사항

- vod와 content는 같은 id를 바탕으로 구성한 것이라고 함. 문의 답변이 달리는대로 공유할 예정

**Comment by Junoflows** [comment]
마무리 되면 VOD랑 Content 합쳐봅시다!
